apiVersion: v1
kind: Secret
metadata:
  name: counter-database
type: Opaque
stringData:
  database-host: counter-database
  database-name: counterdb
  database-user: counteruser
  database-password: counterpassword